openapi: 3.0.0
info:
  title: Converted from api.yaml with typeconv
  version: '1'
paths: {}
components:
  schemas:
    Book:
      properties:
        title:
          type: string
        description:
          type: string
        authors:
          items:
            $ref: '#/components/schema/Author'
          type: array
        type:
          anyOf:
            - $ref: '#/components/schema/BookType'
            - nullable: true
        editions:
          additionalProperties:
            $ref: '#/components/schema/Edition'
          type: object
      required:
        - title
        - authors
        - type
        - editions
      additionalProperties: false
      type: object
    Author:
      properties:
        name:
          type: string
      required:
        - name
      additionalProperties: false
      type: object
    Edition:
      properties:
        name:
          type: string
        date:
          $ref: '#/components/schema/Date'
      required:
        - name
        - date
      additionalProperties: false
      type: object
