openapi: 3.0.0
info:
  title: Converted from api.yaml with typeconv
  version: '1'
components:
  schemas:
    SMSConversationMessage:
      properties:
        direction:
          type: string
        isSuccessful:
          type: boolean
        isAutomatic:
          type: boolean
        timestamp:
          type: string
        text:
          type: string
      required:
        - direction
        - isSuccessful
        - isAutomatic
        - timestamp
        - text
      additionalProperties: false
      type: object
    SMSConversation:
      properties:
        phoneNumber:
          type: string
        lastInteractionAt:
          type: string
        lastMessageText:
          type: string
        lastMessageFailed:
          type: boolean
      required:
        - phoneNumber
        - lastInteractionAt
        - lastMessageText
        - lastMessageFailed
      additionalProperties: false
      type: object
    GetConversationsResponse:
      properties:
        data:
          items:
            $ref: '#/components/schemas/SMSConversation'
          type: array
      required:
        - data
      additionalProperties: false
      type: object
    GetConversationMessagesResponse:
      properties:
        data:
          items:
            $ref: '#/components/schemas/SMSConversationMessage'
          type: array
      required:
        - data
      additionalProperties: false
      type: object
    SendMessageToConversationRequest:
      properties:
        text:
          type: string
      required:
        - text
      additionalProperties: false
      type: object
    SendMessageToConversationResponse:
      properties:
        error: {}
      additionalProperties: false
      type: object
paths:
  # Site api endpoints
  /sms-conversations:
    get:
      summary: List of SMS conversations
      responses:
        200:
          $ref: '#/components/schemas/GetConversationsResponse'
  /sms-conversation/{phoneNumber}:
    get:
      summary: List of SMS conversation messages to a given phone number
      parameters:
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: Phone number
      responses:
        200:
          $ref: '#/components/schemas/GetConversationMessagesResponse'
  /sms-conversations/{phoneNumber}/message:
    post:
      summary: Send test message to a given conversation
      parameters:
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: Phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageToConversationRequest'
      responses:
        200:
          $ref: '#/components/schemas/SendMessageToConversationResponse'

  # Microservice API endpoints
  /sites/{siteID}/sms-conversations:
    get:
      summary: List of SMS conversations
      parameters:
        - in: path
          name: siteID
          schema:
            type: string
          required: true
          description: Site id
      responses:
        200:
          $ref: '#/components/schemas/GetConversationsResponse'
  /sites/{siteID}/sms-conversations/{phoneNumber}:
    get:
      summary: List of SMS conversation messages to a given phone number
      parameters:
        - in: path
          name: siteID
          schema:
            type: string
          required: true
          description: Site id
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: Phone number
      responses:
        200:
          $ref: '#/components/schemas/GetConversationMessagesResponse'
  /sites/{siteID}/sms-conversations/{phoneNumber}/message:
    post:
      summary: Send test message to a given conversation
      parameters:
        - in: path
          name: siteID
          schema:
            type: string
          required: true
          description: Site id
        - in: path
          name: phoneNumber
          schema:
            type: string
          required: true
          description: Phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageToConversationRequest'
      responses:
        200:
          $ref: '#/components/schemas/SendMessageToConversationResponse'
