openapi: 3.0.0
info:
  title: /sms-conversion
  version: '1'
  description: ''
servers:
  - url: /
paths:
  /sms-conversations:
    get:
      responses:
        '200':
          $ref: '#/components/schemas/GetConversationsResponse'
      summary: List of SMS conversations
  '/sms-conversation/{phoneNumber}':
    get:
      parameters:
        - description: Phone number
          explode: false
          in: path
          name: phoneNumber
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          $ref: '#/components/schemas/GetConversationMessagesResponse'
      summary: List of SMS conversation messages to a given phone number
  '/sms-conversations/{phoneNumber}/message':
    post:
      parameters:
        - description: Phone number
          explode: false
          in: path
          name: phoneNumber
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageToConversationRequest'
        required: true
      responses:
        '200':
          $ref: '#/components/schemas/SendMessageToConversationResponse'
      summary: Send test message to a given conversation
  '/sites/{siteID}/sms-conversations':
    get:
      parameters:
        - description: Site id
          explode: false
          in: path
          name: siteID
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          $ref: '#/components/schemas/GetConversationsResponse'
      summary: List of SMS conversations
  '/sites/{siteID}/sms-conversations/{phoneNumber}':
    get:
      parameters:
        - description: Site id
          explode: false
          in: path
          name: siteID
          required: true
          schema:
            type: string
          style: simple
        - description: Phone number
          explode: false
          in: path
          name: phoneNumber
          required: true
          schema:
            type: string
          style: simple
      responses:
        '200':
          $ref: '#/components/schemas/GetConversationMessagesResponse'
      summary: List of SMS conversation messages to a given phone number
  '/sites/{siteID}/sms-conversations/{phoneNumber}/message':
    post:
      parameters:
        - description: Site id
          explode: false
          in: path
          name: siteID
          required: true
          schema:
            type: string
          style: simple
        - description: Phone number
          explode: false
          in: path
          name: phoneNumber
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendMessageToConversationRequest'
        required: true
      responses:
        '200':
          $ref: '#/components/schemas/SendMessageToConversationResponse'
      summary: Send test message to a given conversation
components:
  schemas:
    SMSConversationMessage:
      additionalProperties: false
      properties:
        direction:
          type: string
        isSuccessful:
          type: boolean
        isAutomatic:
          type: boolean
        timestamp:
          type: string
        text:
          type: string
      required:
        - direction
        - isAutomatic
        - isSuccessful
        - text
        - timestamp
      type: object
    SMSConversation:
      additionalProperties: false
      properties:
        phoneNumber:
          type: string
        lastInteractionAt:
          type: string
        lastMessageText:
          type: string
        lastMessageFailed:
          type: boolean
      required:
        - lastInteractionAt
        - lastMessageFailed
        - lastMessageText
        - phoneNumber
      type: object
    GetConversationsResponse:
      additionalProperties: false
      properties:
        data:
          items:
            $ref: '#/components/schemas/SMSConversation'
          type: array
      required:
        - data
      type: object
    GetConversationMessagesResponse:
      additionalProperties: false
      properties:
        data:
          items:
            $ref: '#/components/schemas/SMSConversationMessage'
          type: array
      required:
        - data
      type: object
    SendMessageToConversationRequest:
      additionalProperties: false
      example:
        text: text
      properties:
        text:
          type: string
      required:
        - text
      type: object
    SendMessageToConversationResponse:
      additionalProperties: false
      properties:
        error: {}
      type: object
