/*
 * Converted from api.yaml with typeconv
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SMSConversation struct for SMSConversation
type SMSConversation struct {
	PhoneNumber string `json:"phoneNumber"`
	LastInteractionAt string `json:"lastInteractionAt"`
	LastMessageText string `json:"lastMessageText"`
	LastMessageFailed bool `json:"lastMessageFailed"`
}

// NewSMSConversation instantiates a new SMSConversation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSMSConversation(phoneNumber string, lastInteractionAt string, lastMessageText string, lastMessageFailed bool) *SMSConversation {
	this := SMSConversation{}
	this.PhoneNumber = phoneNumber
	this.LastInteractionAt = lastInteractionAt
	this.LastMessageText = lastMessageText
	this.LastMessageFailed = lastMessageFailed
	return &this
}

// NewSMSConversationWithDefaults instantiates a new SMSConversation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSMSConversationWithDefaults() *SMSConversation {
	this := SMSConversation{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *SMSConversation) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *SMSConversation) GetPhoneNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *SMSConversation) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetLastInteractionAt returns the LastInteractionAt field value
func (o *SMSConversation) GetLastInteractionAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastInteractionAt
}

// GetLastInteractionAtOk returns a tuple with the LastInteractionAt field value
// and a boolean to check if the value has been set.
func (o *SMSConversation) GetLastInteractionAtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastInteractionAt, true
}

// SetLastInteractionAt sets field value
func (o *SMSConversation) SetLastInteractionAt(v string) {
	o.LastInteractionAt = v
}

// GetLastMessageText returns the LastMessageText field value
func (o *SMSConversation) GetLastMessageText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastMessageText
}

// GetLastMessageTextOk returns a tuple with the LastMessageText field value
// and a boolean to check if the value has been set.
func (o *SMSConversation) GetLastMessageTextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastMessageText, true
}

// SetLastMessageText sets field value
func (o *SMSConversation) SetLastMessageText(v string) {
	o.LastMessageText = v
}

// GetLastMessageFailed returns the LastMessageFailed field value
func (o *SMSConversation) GetLastMessageFailed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.LastMessageFailed
}

// GetLastMessageFailedOk returns a tuple with the LastMessageFailed field value
// and a boolean to check if the value has been set.
func (o *SMSConversation) GetLastMessageFailedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastMessageFailed, true
}

// SetLastMessageFailed sets field value
func (o *SMSConversation) SetLastMessageFailed(v bool) {
	o.LastMessageFailed = v
}

func (o SMSConversation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if true {
		toSerialize["lastInteractionAt"] = o.LastInteractionAt
	}
	if true {
		toSerialize["lastMessageText"] = o.LastMessageText
	}
	if true {
		toSerialize["lastMessageFailed"] = o.LastMessageFailed
	}
	return json.Marshal(toSerialize)
}

type NullableSMSConversation struct {
	value *SMSConversation
	isSet bool
}

func (v NullableSMSConversation) Get() *SMSConversation {
	return v.value
}

func (v *NullableSMSConversation) Set(val *SMSConversation) {
	v.value = val
	v.isSet = true
}

func (v NullableSMSConversation) IsSet() bool {
	return v.isSet
}

func (v *NullableSMSConversation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSMSConversation(val *SMSConversation) *NullableSMSConversation {
	return &NullableSMSConversation{value: val, isSet: true}
}

func (v NullableSMSConversation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSMSConversation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


