/*
 * Converted from api.yaml with typeconv
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SendMessageToConversationRequest struct for SendMessageToConversationRequest
type SendMessageToConversationRequest struct {
	Text string `json:"text"`
}

// NewSendMessageToConversationRequest instantiates a new SendMessageToConversationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMessageToConversationRequest(text string) *SendMessageToConversationRequest {
	this := SendMessageToConversationRequest{}
	this.Text = text
	return &this
}

// NewSendMessageToConversationRequestWithDefaults instantiates a new SendMessageToConversationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMessageToConversationRequestWithDefaults() *SendMessageToConversationRequest {
	this := SendMessageToConversationRequest{}
	return &this
}

// GetText returns the Text field value
func (o *SendMessageToConversationRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *SendMessageToConversationRequest) GetTextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *SendMessageToConversationRequest) SetText(v string) {
	o.Text = v
}

func (o SendMessageToConversationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableSendMessageToConversationRequest struct {
	value *SendMessageToConversationRequest
	isSet bool
}

func (v NullableSendMessageToConversationRequest) Get() *SendMessageToConversationRequest {
	return v.value
}

func (v *NullableSendMessageToConversationRequest) Set(val *SendMessageToConversationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMessageToConversationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMessageToConversationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMessageToConversationRequest(val *SendMessageToConversationRequest) *NullableSendMessageToConversationRequest {
	return &NullableSendMessageToConversationRequest{value: val, isSet: true}
}

func (v NullableSendMessageToConversationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMessageToConversationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


