/*
 * Converted from api.yaml with typeconv
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SendMessageToConversationResponse struct for SendMessageToConversationResponse
type SendMessageToConversationResponse struct {
	Error interface{} `json:"error,omitempty"`
}

// NewSendMessageToConversationResponse instantiates a new SendMessageToConversationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMessageToConversationResponse() *SendMessageToConversationResponse {
	this := SendMessageToConversationResponse{}
	return &this
}

// NewSendMessageToConversationResponseWithDefaults instantiates a new SendMessageToConversationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMessageToConversationResponseWithDefaults() *SendMessageToConversationResponse {
	this := SendMessageToConversationResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendMessageToConversationResponse) GetError() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendMessageToConversationResponse) GetErrorOk() (*interface{}, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return &o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SendMessageToConversationResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given interface{} and assigns it to the Error field.
func (o *SendMessageToConversationResponse) SetError(v interface{}) {
	o.Error = v
}

func (o SendMessageToConversationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableSendMessageToConversationResponse struct {
	value *SendMessageToConversationResponse
	isSet bool
}

func (v NullableSendMessageToConversationResponse) Get() *SendMessageToConversationResponse {
	return v.value
}

func (v *NullableSendMessageToConversationResponse) Set(val *SendMessageToConversationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMessageToConversationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMessageToConversationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMessageToConversationResponse(val *SendMessageToConversationResponse) *NullableSendMessageToConversationResponse {
	return &NullableSendMessageToConversationResponse{value: val, isSet: true}
}

func (v NullableSendMessageToConversationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMessageToConversationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


