/*
 * Converted from api.yaml with typeconv
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SMSConversationMessage struct for SMSConversationMessage
type SMSConversationMessage struct {
	Direction string `json:"direction"`
	IsSuccessful bool `json:"isSuccessful"`
	IsAutomatic bool `json:"isAutomatic"`
	Timestamp string `json:"timestamp"`
	Text string `json:"text"`
}

// NewSMSConversationMessage instantiates a new SMSConversationMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSMSConversationMessage(direction string, isSuccessful bool, isAutomatic bool, timestamp string, text string) *SMSConversationMessage {
	this := SMSConversationMessage{}
	this.Direction = direction
	this.IsSuccessful = isSuccessful
	this.IsAutomatic = isAutomatic
	this.Timestamp = timestamp
	this.Text = text
	return &this
}

// NewSMSConversationMessageWithDefaults instantiates a new SMSConversationMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSMSConversationMessageWithDefaults() *SMSConversationMessage {
	this := SMSConversationMessage{}
	return &this
}

// GetDirection returns the Direction field value
func (o *SMSConversationMessage) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *SMSConversationMessage) GetDirectionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *SMSConversationMessage) SetDirection(v string) {
	o.Direction = v
}

// GetIsSuccessful returns the IsSuccessful field value
func (o *SMSConversationMessage) GetIsSuccessful() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSuccessful
}

// GetIsSuccessfulOk returns a tuple with the IsSuccessful field value
// and a boolean to check if the value has been set.
func (o *SMSConversationMessage) GetIsSuccessfulOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsSuccessful, true
}

// SetIsSuccessful sets field value
func (o *SMSConversationMessage) SetIsSuccessful(v bool) {
	o.IsSuccessful = v
}

// GetIsAutomatic returns the IsAutomatic field value
func (o *SMSConversationMessage) GetIsAutomatic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAutomatic
}

// GetIsAutomaticOk returns a tuple with the IsAutomatic field value
// and a boolean to check if the value has been set.
func (o *SMSConversationMessage) GetIsAutomaticOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsAutomatic, true
}

// SetIsAutomatic sets field value
func (o *SMSConversationMessage) SetIsAutomatic(v bool) {
	o.IsAutomatic = v
}

// GetTimestamp returns the Timestamp field value
func (o *SMSConversationMessage) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *SMSConversationMessage) GetTimestampOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *SMSConversationMessage) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetText returns the Text field value
func (o *SMSConversationMessage) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *SMSConversationMessage) GetTextOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *SMSConversationMessage) SetText(v string) {
	o.Text = v
}

func (o SMSConversationMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["direction"] = o.Direction
	}
	if true {
		toSerialize["isSuccessful"] = o.IsSuccessful
	}
	if true {
		toSerialize["isAutomatic"] = o.IsAutomatic
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableSMSConversationMessage struct {
	value *SMSConversationMessage
	isSet bool
}

func (v NullableSMSConversationMessage) Get() *SMSConversationMessage {
	return v.value
}

func (v *NullableSMSConversationMessage) Set(val *SMSConversationMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSMSConversationMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSMSConversationMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSMSConversationMessage(val *SMSConversationMessage) *NullableSMSConversationMessage {
	return &NullableSMSConversationMessage{value: val, isSet: true}
}

func (v NullableSMSConversationMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSMSConversationMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


